language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - acl

install:
  - composer self-update
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
